### ISSUE TITLE
two questions

### ISSUE THREAD

**Issue by funkyfuture** [bodsch/ansible-loki#1]
ciao Bodo, i'm evaluating this Ansible role and so far i'm convinced that it is much better engineered than the one i'm currently using. i have two questions that came up in the process:

1) i haven't seen the pattern how you handle default configuration values until now (defining them in a `vars` file instead of a `defaults/main.yml`). is that because it allows users to override particular nested values (by merging) instead of having to re-define a whole config object?

2) since i deploy loki on only one host that can reach the public internet, the download and distribution via localhost is a waste of resouces in my case. would you be interested in a patch that allows a direct download from the target host as alternative?

best regards!

**Comment by bodsch** [comment]
Moin!

Thank you for your praise! :)
 
> i haven't seen the pattern how you handle default configuration values until now (defining them in a `vars` file instead of a `defaults/main.yml`). is that because it allows users to override particular nested values (by merging) instead of having to re-define a whole config object?

Yes, it is possible to overwrite all configuration variables.
The ones defined in vars are - for me - sensibly pre-assigned.
You can see how the whole thing works in the [molecule tests](https://github.com/bodsch/ansible-loki/blob/main/molecule/default/group_vars/all/vars.yml). 

>  since i deploy loki on only one host that can reach the public internet, the download and distribution via localhost is a waste of resouces in my case. would you be interested in a patch that allows a direct download from the target host as alternative?

I support several large environments with this role where none of the target hosts have an internet connection. Hence the solution via the ansible-controller.
Of course you can submit a patch, but please do so in such a way that the path is then optionally selectable to ensure the previous function.

Regards, Bodo

**Comment by funkyfuture** [comment]
tachchen, a'ight, thanks.

> but please do so in such a way that the path is then optionally selectable to ensure the previous function.

sure.

bis denne!
